"c = 0\n"
"Raylib.InitWindow(720, 405, 'raylib/mruby')\n"
"Raylib.SetTargetFPS(60)\n"
"until Raylib.WindowShouldClose()\n"
"    Raylib.BeginDrawing()\n"
"    bg = Raylib::Color.new(c,c,c,255)\n"
"    Raylib.ClearBackground(bg)\n"
"    Raylib.DrawFPS(720 - 100, 16)\n"
"    Raylib.EndDrawing()\n"
"    c = (c + 1) % 255\n"
"    p [Raylib::Vector3.size, bg.class.size]\n"
"end\n"
"Raylib.CloseWindow()\n"
