# Yet another raylib wrapper for Ruby
#
# * https://github.com/vaiorabbit/raylib-bindings
#
# [NOTICE] Autogenerated. Do not edit.

require 'ffi'

module Raylib
  extend FFI::Library

  # Define/Macro

  SUPPORT_MODULE_RSHAPES = 1
  SUPPORT_MODULE_RTEXTURES = 1
  SUPPORT_MODULE_RTEXT = 1 # WARNING: It requires SUPPORT_MODULE_RTEXTURES to load sprite font textures
  SUPPORT_MODULE_RMODELS = 1
  SUPPORT_MODULE_RAUDIO = 1
  SUPPORT_CAMERA_SYSTEM = 1
  SUPPORT_GESTURES_SYSTEM = 1
  SUPPORT_MOUSE_GESTURES = 1
  SUPPORT_SSH_KEYBOARD_RPI = 1
  SUPPORT_WINMM_HIGHRES_TIMER = 1
  SUPPORT_PARTIALBUSY_WAIT_LOOP = 1
  SUPPORT_SCREEN_CAPTURE = 1
  SUPPORT_GIF_RECORDING = 1
  SUPPORT_COMPRESSION_API = 1
  MAX_FILEPATH_CAPACITY = 8192 # Maximum file paths capacity
  MAX_FILEPATH_LENGTH = 4096 # Maximum length for filepaths (Linux PATH_MAX default value)
  MAX_KEYBOARD_KEYS = 512 # Maximum number of keyboard keys supported
  MAX_MOUSE_BUTTONS = 8 # Maximum number of mouse buttons supported
  MAX_GAMEPADS = 4 # Maximum number of gamepads supported
  MAX_GAMEPAD_AXIS = 8 # Maximum number of axis supported (per gamepad)
  MAX_GAMEPAD_BUTTONS = 32 # Maximum number of buttons supported (per gamepad)
  MAX_TOUCH_POINTS = 8 # Maximum number of touch points supported
  MAX_KEY_PRESSED_QUEUE = 16 # Maximum number of keys in the key input queue
  MAX_CHAR_PRESSED_QUEUE = 16 # Maximum number of characters in the char input queue
  MAX_DECOMPRESSION_SIZE = 64 # Max size allocated for decompression in MB
  RL_DEFAULT_BATCH_BUFFERS = 1 # Default number of batch buffers (multi-buffering)
  RL_DEFAULT_BATCH_DRAWCALLS = 256 # Default number of batch draw calls (by state changes: mode, texture)
  RL_DEFAULT_BATCH_MAX_TEXTURE_UNITS = 4 # Maximum number of textures units that can be activated on batch drawing (SetShaderValueTexture())
  RL_MAX_MATRIX_STACK_SIZE = 32 # Maximum size of internal Matrix stack
  RL_MAX_SHADER_LOCATIONS = 32 # Maximum number of shader locations supported
  RL_CULL_DISTANCE_NEAR = 0.01 # Default projection matrix near cull distance
  RL_CULL_DISTANCE_FAR = 1000.0 # Default projection matrix far cull distance
  RL_DEFAULT_SHADER_ATTRIB_NAME_POSITION = "vertexPosition" # Binded by default to shader location: 0
  RL_DEFAULT_SHADER_ATTRIB_NAME_TEXCOORD = "vertexTexCoord" # Binded by default to shader location: 1
  RL_DEFAULT_SHADER_ATTRIB_NAME_NORMAL = "vertexNormal" # Binded by default to shader location: 2
  RL_DEFAULT_SHADER_ATTRIB_NAME_COLOR = "vertexColor" # Binded by default to shader location: 3
  RL_DEFAULT_SHADER_ATTRIB_NAME_TANGENT = "vertexTangent" # Binded by default to shader location: 4
  RL_DEFAULT_SHADER_ATTRIB_NAME_TEXCOORD2 = "vertexTexCoord2" # Binded by default to shader location: 5
  RL_DEFAULT_SHADER_UNIFORM_NAME_MVP = "mvp" # model-view-projection matrix
  RL_DEFAULT_SHADER_UNIFORM_NAME_VIEW = "matView" # view matrix
  RL_DEFAULT_SHADER_UNIFORM_NAME_PROJECTION = "matProjection" # projection matrix
  RL_DEFAULT_SHADER_UNIFORM_NAME_MODEL = "matModel" # model matrix
  RL_DEFAULT_SHADER_UNIFORM_NAME_NORMAL = "matNormal" # normal matrix (transpose(inverse(matModelView))
  RL_DEFAULT_SHADER_UNIFORM_NAME_COLOR = "colDiffuse" # color diffuse (base tint color, multiplied by texture color)
  RL_DEFAULT_SHADER_SAMPLER2D_NAME_TEXTURE0 = "texture0" # texture0 (texture slot active 0)
  RL_DEFAULT_SHADER_SAMPLER2D_NAME_TEXTURE1 = "texture1" # texture1 (texture slot active 1)
  RL_DEFAULT_SHADER_SAMPLER2D_NAME_TEXTURE2 = "texture2" # texture2 (texture slot active 2)
  SUPPORT_QUADS_DRAW_MODE = 1
  SUPPORT_FILEFORMAT_PNG = 1
  SUPPORT_FILEFORMAT_GIF = 1
  SUPPORT_FILEFORMAT_QOI = 1
  SUPPORT_FILEFORMAT_DDS = 1
  SUPPORT_FILEFORMAT_HDR = 1
  SUPPORT_IMAGE_EXPORT = 1
  SUPPORT_IMAGE_GENERATION = 1
  SUPPORT_IMAGE_MANIPULATION = 1
  SUPPORT_DEFAULT_FONT = 1
  SUPPORT_FILEFORMAT_FNT = 1
  SUPPORT_FILEFORMAT_TTF = 1
  SUPPORT_TEXT_MANIPULATION = 1
  MAX_TEXT_BUFFER_LENGTH = 1024 # Size of internal static buffers used on some functions:
  MAX_TEXTSPLIT_COUNT = 128 # Maximum number of substrings to split: TextSplit()
  SUPPORT_FILEFORMAT_OBJ = 1
  SUPPORT_FILEFORMAT_MTL = 1
  SUPPORT_FILEFORMAT_IQM = 1
  SUPPORT_FILEFORMAT_GLTF = 1
  SUPPORT_FILEFORMAT_VOX = 1
  SUPPORT_FILEFORMAT_M3D = 1
  SUPPORT_MESH_GENERATION = 1
  MAX_MATERIAL_MAPS = 12 # Maximum number of shader maps supported
  MAX_MESH_VERTEX_BUFFERS = 7 # Maximum vertex buffers (VBO) per mesh
  SUPPORT_FILEFORMAT_WAV = 1
  SUPPORT_FILEFORMAT_OGG = 1
  SUPPORT_FILEFORMAT_XM = 1
  SUPPORT_FILEFORMAT_MOD = 1
  SUPPORT_FILEFORMAT_MP3 = 1
  AUDIO_DEVICE_FORMAT = "ma_format_f32" # Device output format (miniaudio: float-32bit)
  AUDIO_DEVICE_CHANNELS = 2 # Device output channels: stereo
  AUDIO_DEVICE_SAMPLE_RATE = 0 # Device sample rate (device default)
  MAX_AUDIO_BUFFER_POOL_CHANNELS = 16 # Maximum number of audio pool channels
  SUPPORT_STANDARD_FILEIO = 1
  SUPPORT_TRACELOG = 1
  MAX_TRACELOG_MSG_LENGTH = 128 # Max length of one trace-log message

end
