# Yet another raylib wrapper for Ruby
#
# * https://github.com/vaiorabbit/raylib-bindings
#
# [NOTICE] Autogenerated. Do not edit.

require 'ffi'

module Raylib
  extend FFI::Library
  # Define/Macro

  RAYLIB_VERSION = "4.5-dev"
  DEG2RAD = Math::PI / 180.0
  RAD2DEG = 180.0 / Math::PI

  # Enum

  FLAG_VSYNC_HINT = 64 # Set to try enabling V-Sync on GPU
  FLAG_FULLSCREEN_MODE = 2 # Set to run program in fullscreen
  FLAG_WINDOW_RESIZABLE = 4 # Set to allow resizable window
  FLAG_WINDOW_UNDECORATED = 8 # Set to disable window decoration (frame and buttons)
  FLAG_WINDOW_HIDDEN = 128 # Set to hide window
  FLAG_WINDOW_MINIMIZED = 512 # Set to minimize window (iconify)
  FLAG_WINDOW_MAXIMIZED = 1024 # Set to maximize window (expanded to monitor)
  FLAG_WINDOW_UNFOCUSED = 2048 # Set to window non focused
  FLAG_WINDOW_TOPMOST = 4096 # Set to window always on top
  FLAG_WINDOW_ALWAYS_RUN = 256 # Set to allow windows running while minimized
  FLAG_WINDOW_TRANSPARENT = 16 # Set to allow transparent framebuffer
  FLAG_WINDOW_HIGHDPI = 8192 # Set to support HighDPI
  FLAG_WINDOW_MOUSE_PASSTHROUGH = 16384 # Set to support mouse passthrough, only supported when FLAG_WINDOW_UNDECORATED
  FLAG_MSAA_4X_HINT = 32 # Set to try enabling MSAA 4X
  FLAG_INTERLACED_HINT = 65536 # Set to try enabling interlaced video format (for V3D)
  LOG_ALL = 0 # Display all logs
  LOG_TRACE = 1 # Trace logging, intended for internal use only
  LOG_DEBUG = 2 # Debug logging, used for internal debugging, it should be disabled on release builds
  LOG_INFO = 3 # Info logging, used for program execution info
  LOG_WARNING = 4 # Warning logging, used on recoverable failures
  LOG_ERROR = 5 # Error logging, used on unrecoverable failures
  LOG_FATAL = 6 # Fatal logging, used to abort program: exit(EXIT_FAILURE)
  LOG_NONE = 7 # Disable logging
  KEY_NULL = 0 # Key: NULL, used for no key pressed
  KEY_APOSTROPHE = 39 # Key: '
  KEY_COMMA = 44 # Key: ,
  KEY_MINUS = 45 # Key: -
  KEY_PERIOD = 46 # Key: .
  KEY_SLASH = 47 # Key: /
  KEY_ZERO = 48 # Key: 0
  KEY_ONE = 49 # Key: 1
  KEY_TWO = 50 # Key: 2
  KEY_THREE = 51 # Key: 3
  KEY_FOUR = 52 # Key: 4
  KEY_FIVE = 53 # Key: 5
  KEY_SIX = 54 # Key: 6
  KEY_SEVEN = 55 # Key: 7
  KEY_EIGHT = 56 # Key: 8
  KEY_NINE = 57 # Key: 9
  KEY_SEMICOLON = 59 # Key: ;
  KEY_EQUAL = 61 # Key: =
  KEY_A = 65 # Key: A | a
  KEY_B = 66 # Key: B | b
  KEY_C = 67 # Key: C | c
  KEY_D = 68 # Key: D | d
  KEY_E = 69 # Key: E | e
  KEY_F = 70 # Key: F | f
  KEY_G = 71 # Key: G | g
  KEY_H = 72 # Key: H | h
  KEY_I = 73 # Key: I | i
  KEY_J = 74 # Key: J | j
  KEY_K = 75 # Key: K | k
  KEY_L = 76 # Key: L | l
  KEY_M = 77 # Key: M | m
  KEY_N = 78 # Key: N | n
  KEY_O = 79 # Key: O | o
  KEY_P = 80 # Key: P | p
  KEY_Q = 81 # Key: Q | q
  KEY_R = 82 # Key: R | r
  KEY_S = 83 # Key: S | s
  KEY_T = 84 # Key: T | t
  KEY_U = 85 # Key: U | u
  KEY_V = 86 # Key: V | v
  KEY_W = 87 # Key: W | w
  KEY_X = 88 # Key: X | x
  KEY_Y = 89 # Key: Y | y
  KEY_Z = 90 # Key: Z | z
  KEY_LEFT_BRACKET = 91 # Key: [
  KEY_BACKSLASH = 92 # Key: '\'
  KEY_RIGHT_BRACKET = 93 # Key: ]
  KEY_GRAVE = 96 # Key: `
  KEY_SPACE = 32 # Key: Space
  KEY_ESCAPE = 256 # Key: Esc
  KEY_ENTER = 257 # Key: Enter
  KEY_TAB = 258 # Key: Tab
  KEY_BACKSPACE = 259 # Key: Backspace
  KEY_INSERT = 260 # Key: Ins
  KEY_DELETE = 261 # Key: Del
  KEY_RIGHT = 262 # Key: Cursor right
  KEY_LEFT = 263 # Key: Cursor left
  KEY_DOWN = 264 # Key: Cursor down
  KEY_UP = 265 # Key: Cursor up
  KEY_PAGE_UP = 266 # Key: Page up
  KEY_PAGE_DOWN = 267 # Key: Page down
  KEY_HOME = 268 # Key: Home
  KEY_END = 269 # Key: End
  KEY_CAPS_LOCK = 280 # Key: Caps lock
  KEY_SCROLL_LOCK = 281 # Key: Scroll down
  KEY_NUM_LOCK = 282 # Key: Num lock
  KEY_PRINT_SCREEN = 283 # Key: Print screen
  KEY_PAUSE = 284 # Key: Pause
  KEY_F1 = 290 # Key: F1
  KEY_F2 = 291 # Key: F2
  KEY_F3 = 292 # Key: F3
  KEY_F4 = 293 # Key: F4
  KEY_F5 = 294 # Key: F5
  KEY_F6 = 295 # Key: F6
  KEY_F7 = 296 # Key: F7
  KEY_F8 = 297 # Key: F8
  KEY_F9 = 298 # Key: F9
  KEY_F10 = 299 # Key: F10
  KEY_F11 = 300 # Key: F11
  KEY_F12 = 301 # Key: F12
  KEY_LEFT_SHIFT = 340 # Key: Shift left
  KEY_LEFT_CONTROL = 341 # Key: Control left
  KEY_LEFT_ALT = 342 # Key: Alt left
  KEY_LEFT_SUPER = 343 # Key: Super left
  KEY_RIGHT_SHIFT = 344 # Key: Shift right
  KEY_RIGHT_CONTROL = 345 # Key: Control right
  KEY_RIGHT_ALT = 346 # Key: Alt right
  KEY_RIGHT_SUPER = 347 # Key: Super right
  KEY_KB_MENU = 348 # Key: KB menu
  KEY_KP_0 = 320 # Key: Keypad 0
  KEY_KP_1 = 321 # Key: Keypad 1
  KEY_KP_2 = 322 # Key: Keypad 2
  KEY_KP_3 = 323 # Key: Keypad 3
  KEY_KP_4 = 324 # Key: Keypad 4
  KEY_KP_5 = 325 # Key: Keypad 5
  KEY_KP_6 = 326 # Key: Keypad 6
  KEY_KP_7 = 327 # Key: Keypad 7
  KEY_KP_8 = 328 # Key: Keypad 8
  KEY_KP_9 = 329 # Key: Keypad 9
  KEY_KP_DECIMAL = 330 # Key: Keypad .
  KEY_KP_DIVIDE = 331 # Key: Keypad /
  KEY_KP_MULTIPLY = 332 # Key: Keypad *
  KEY_KP_SUBTRACT = 333 # Key: Keypad -
  KEY_KP_ADD = 334 # Key: Keypad +
  KEY_KP_ENTER = 335 # Key: Keypad Enter
  KEY_KP_EQUAL = 336 # Key: Keypad =
  KEY_BACK = 4 # Key: Android back button
  KEY_MENU = 82 # Key: Android menu button
  KEY_VOLUME_UP = 24 # Key: Android volume up button
  KEY_VOLUME_DOWN = 25 # Key: Android volume down button
  MOUSE_BUTTON_LEFT = 0 # Mouse button left
  MOUSE_BUTTON_RIGHT = 1 # Mouse button right
  MOUSE_BUTTON_MIDDLE = 2 # Mouse button middle (pressed wheel)
  MOUSE_BUTTON_SIDE = 3 # Mouse button side (advanced mouse device)
  MOUSE_BUTTON_EXTRA = 4 # Mouse button extra (advanced mouse device)
  MOUSE_BUTTON_FORWARD = 5 # Mouse button forward (advanced mouse device)
  MOUSE_BUTTON_BACK = 6 # Mouse button back (advanced mouse device)
  MOUSE_CURSOR_DEFAULT = 0 # Default pointer shape
  MOUSE_CURSOR_ARROW = 1 # Arrow shape
  MOUSE_CURSOR_IBEAM = 2 # Text writing cursor shape
  MOUSE_CURSOR_CROSSHAIR = 3 # Cross shape
  MOUSE_CURSOR_POINTING_HAND = 4 # Pointing hand cursor
  MOUSE_CURSOR_RESIZE_EW = 5 # Horizontal resize/move arrow shape
  MOUSE_CURSOR_RESIZE_NS = 6 # Vertical resize/move arrow shape
  MOUSE_CURSOR_RESIZE_NWSE = 7 # Top-left to bottom-right diagonal resize/move arrow shape
  MOUSE_CURSOR_RESIZE_NESW = 8 # The top-right to bottom-left diagonal resize/move arrow shape
  MOUSE_CURSOR_RESIZE_ALL = 9 # The omni-directional resize/move cursor shape
  MOUSE_CURSOR_NOT_ALLOWED = 10 # The operation-not-allowed shape
  GAMEPAD_BUTTON_UNKNOWN = 0 # Unknown button, just for error checking
  GAMEPAD_BUTTON_LEFT_FACE_UP = 1 # Gamepad left DPAD up button
  GAMEPAD_BUTTON_LEFT_FACE_RIGHT = 2 # Gamepad left DPAD right button
  GAMEPAD_BUTTON_LEFT_FACE_DOWN = 3 # Gamepad left DPAD down button
  GAMEPAD_BUTTON_LEFT_FACE_LEFT = 4 # Gamepad left DPAD left button
  GAMEPAD_BUTTON_RIGHT_FACE_UP = 5 # Gamepad right button up (i.e. PS3: Triangle, Xbox: Y)
  GAMEPAD_BUTTON_RIGHT_FACE_RIGHT = 6 # Gamepad right button right (i.e. PS3: Square, Xbox: X)
  GAMEPAD_BUTTON_RIGHT_FACE_DOWN = 7 # Gamepad right button down (i.e. PS3: Cross, Xbox: A)
  GAMEPAD_BUTTON_RIGHT_FACE_LEFT = 8 # Gamepad right button left (i.e. PS3: Circle, Xbox: B)
  GAMEPAD_BUTTON_LEFT_TRIGGER_1 = 9 # Gamepad top/back trigger left (first), it could be a trailing button
  GAMEPAD_BUTTON_LEFT_TRIGGER_2 = 10 # Gamepad top/back trigger left (second), it could be a trailing button
  GAMEPAD_BUTTON_RIGHT_TRIGGER_1 = 11 # Gamepad top/back trigger right (one), it could be a trailing button
  GAMEPAD_BUTTON_RIGHT_TRIGGER_2 = 12 # Gamepad top/back trigger right (second), it could be a trailing button
  GAMEPAD_BUTTON_MIDDLE_LEFT = 13 # Gamepad center buttons, left one (i.e. PS3: Select)
  GAMEPAD_BUTTON_MIDDLE = 14 # Gamepad center buttons, middle one (i.e. PS3: PS, Xbox: XBOX)
  GAMEPAD_BUTTON_MIDDLE_RIGHT = 15 # Gamepad center buttons, right one (i.e. PS3: Start)
  GAMEPAD_BUTTON_LEFT_THUMB = 16 # Gamepad joystick pressed button left
  GAMEPAD_BUTTON_RIGHT_THUMB = 17 # Gamepad joystick pressed button right
  GAMEPAD_AXIS_LEFT_X = 0 # Gamepad left stick X axis
  GAMEPAD_AXIS_LEFT_Y = 1 # Gamepad left stick Y axis
  GAMEPAD_AXIS_RIGHT_X = 2 # Gamepad right stick X axis
  GAMEPAD_AXIS_RIGHT_Y = 3 # Gamepad right stick Y axis
  GAMEPAD_AXIS_LEFT_TRIGGER = 4 # Gamepad back trigger left, pressure level: [1..-1]
  GAMEPAD_AXIS_RIGHT_TRIGGER = 5 # Gamepad back trigger right, pressure level: [1..-1]
  MATERIAL_MAP_ALBEDO = 0 # Albedo material (same as: MATERIAL_MAP_DIFFUSE)
  MATERIAL_MAP_METALNESS = 1 # Metalness material (same as: MATERIAL_MAP_SPECULAR)
  MATERIAL_MAP_NORMAL = 2 # Normal material
  MATERIAL_MAP_ROUGHNESS = 3 # Roughness material
  MATERIAL_MAP_OCCLUSION = 4 # Ambient occlusion material
  MATERIAL_MAP_EMISSION = 5 # Emission material
  MATERIAL_MAP_HEIGHT = 6 # Heightmap material
  MATERIAL_MAP_CUBEMAP = 7 # Cubemap material (NOTE: Uses GL_TEXTURE_CUBE_MAP)
  MATERIAL_MAP_IRRADIANCE = 8 # Irradiance material (NOTE: Uses GL_TEXTURE_CUBE_MAP)
  MATERIAL_MAP_PREFILTER = 9 # Prefilter material (NOTE: Uses GL_TEXTURE_CUBE_MAP)
  MATERIAL_MAP_BRDF = 10 # Brdf material
  SHADER_LOC_VERTEX_POSITION = 0 # Shader location: vertex attribute: position
  SHADER_LOC_VERTEX_TEXCOORD01 = 1 # Shader location: vertex attribute: texcoord01
  SHADER_LOC_VERTEX_TEXCOORD02 = 2 # Shader location: vertex attribute: texcoord02
  SHADER_LOC_VERTEX_NORMAL = 3 # Shader location: vertex attribute: normal
  SHADER_LOC_VERTEX_TANGENT = 4 # Shader location: vertex attribute: tangent
  SHADER_LOC_VERTEX_COLOR = 5 # Shader location: vertex attribute: color
  SHADER_LOC_MATRIX_MVP = 6 # Shader location: matrix uniform: model-view-projection
  SHADER_LOC_MATRIX_VIEW = 7 # Shader location: matrix uniform: view (camera transform)
  SHADER_LOC_MATRIX_PROJECTION = 8 # Shader location: matrix uniform: projection
  SHADER_LOC_MATRIX_MODEL = 9 # Shader location: matrix uniform: model (transform)
  SHADER_LOC_MATRIX_NORMAL = 10 # Shader location: matrix uniform: normal
  SHADER_LOC_VECTOR_VIEW = 11 # Shader location: vector uniform: view
  SHADER_LOC_COLOR_DIFFUSE = 12 # Shader location: vector uniform: diffuse color
  SHADER_LOC_COLOR_SPECULAR = 13 # Shader location: vector uniform: specular color
  SHADER_LOC_COLOR_AMBIENT = 14 # Shader location: vector uniform: ambient color
  SHADER_LOC_MAP_ALBEDO = 15 # Shader location: sampler2d texture: albedo (same as: SHADER_LOC_MAP_DIFFUSE)
  SHADER_LOC_MAP_METALNESS = 16 # Shader location: sampler2d texture: metalness (same as: SHADER_LOC_MAP_SPECULAR)
  SHADER_LOC_MAP_NORMAL = 17 # Shader location: sampler2d texture: normal
  SHADER_LOC_MAP_ROUGHNESS = 18 # Shader location: sampler2d texture: roughness
  SHADER_LOC_MAP_OCCLUSION = 19 # Shader location: sampler2d texture: occlusion
  SHADER_LOC_MAP_EMISSION = 20 # Shader location: sampler2d texture: emission
  SHADER_LOC_MAP_HEIGHT = 21 # Shader location: sampler2d texture: height
  SHADER_LOC_MAP_CUBEMAP = 22 # Shader location: samplerCube texture: cubemap
  SHADER_LOC_MAP_IRRADIANCE = 23 # Shader location: samplerCube texture: irradiance
  SHADER_LOC_MAP_PREFILTER = 24 # Shader location: samplerCube texture: prefilter
  SHADER_LOC_MAP_BRDF = 25 # Shader location: sampler2d texture: brdf
  SHADER_UNIFORM_FLOAT = 0 # Shader uniform type: float
  SHADER_UNIFORM_VEC2 = 1 # Shader uniform type: vec2 (2 float)
  SHADER_UNIFORM_VEC3 = 2 # Shader uniform type: vec3 (3 float)
  SHADER_UNIFORM_VEC4 = 3 # Shader uniform type: vec4 (4 float)
  SHADER_UNIFORM_INT = 4 # Shader uniform type: int
  SHADER_UNIFORM_IVEC2 = 5 # Shader uniform type: ivec2 (2 int)
  SHADER_UNIFORM_IVEC3 = 6 # Shader uniform type: ivec3 (3 int)
  SHADER_UNIFORM_IVEC4 = 7 # Shader uniform type: ivec4 (4 int)
  SHADER_UNIFORM_SAMPLER2D = 8 # Shader uniform type: sampler2d
  SHADER_ATTRIB_FLOAT = 0 # Shader attribute type: float
  SHADER_ATTRIB_VEC2 = 1 # Shader attribute type: vec2 (2 float)
  SHADER_ATTRIB_VEC3 = 2 # Shader attribute type: vec3 (3 float)
  SHADER_ATTRIB_VEC4 = 3 # Shader attribute type: vec4 (4 float)
  PIXELFORMAT_UNCOMPRESSED_GRAYSCALE = 1 # 8 bit per pixel (no alpha)
  PIXELFORMAT_UNCOMPRESSED_GRAY_ALPHA = 2 # 8*2 bpp (2 channels)
  PIXELFORMAT_UNCOMPRESSED_R5G6B5 = 3 # 16 bpp
  PIXELFORMAT_UNCOMPRESSED_R8G8B8 = 4 # 24 bpp
  PIXELFORMAT_UNCOMPRESSED_R5G5B5A1 = 5 # 16 bpp (1 bit alpha)
  PIXELFORMAT_UNCOMPRESSED_R4G4B4A4 = 6 # 16 bpp (4 bit alpha)
  PIXELFORMAT_UNCOMPRESSED_R8G8B8A8 = 7 # 32 bpp
  PIXELFORMAT_UNCOMPRESSED_R32 = 8 # 32 bpp (1 channel - float)
  PIXELFORMAT_UNCOMPRESSED_R32G32B32 = 9 # 32*3 bpp (3 channels - float)
  PIXELFORMAT_UNCOMPRESSED_R32G32B32A32 = 10 # 32*4 bpp (4 channels - float)
  PIXELFORMAT_COMPRESSED_DXT1_RGB = 11 # 4 bpp (no alpha)
  PIXELFORMAT_COMPRESSED_DXT1_RGBA = 12 # 4 bpp (1 bit alpha)
  PIXELFORMAT_COMPRESSED_DXT3_RGBA = 13 # 8 bpp
  PIXELFORMAT_COMPRESSED_DXT5_RGBA = 14 # 8 bpp
  PIXELFORMAT_COMPRESSED_ETC1_RGB = 15 # 4 bpp
  PIXELFORMAT_COMPRESSED_ETC2_RGB = 16 # 4 bpp
  PIXELFORMAT_COMPRESSED_ETC2_EAC_RGBA = 17 # 8 bpp
  PIXELFORMAT_COMPRESSED_PVRT_RGB = 18 # 4 bpp
  PIXELFORMAT_COMPRESSED_PVRT_RGBA = 19 # 4 bpp
  PIXELFORMAT_COMPRESSED_ASTC_4x4_RGBA = 20 # 8 bpp
  PIXELFORMAT_COMPRESSED_ASTC_8x8_RGBA = 21 # 2 bpp
  TEXTURE_FILTER_POINT = 0 # No filter, just pixel approximation
  TEXTURE_FILTER_BILINEAR = 1 # Linear filtering
  TEXTURE_FILTER_TRILINEAR = 2 # Trilinear filtering (linear with mipmaps)
  TEXTURE_FILTER_ANISOTROPIC_4X = 3 # Anisotropic filtering 4x
  TEXTURE_FILTER_ANISOTROPIC_8X = 4 # Anisotropic filtering 8x
  TEXTURE_FILTER_ANISOTROPIC_16X = 5 # Anisotropic filtering 16x
  TEXTURE_WRAP_REPEAT = 0 # Repeats texture in tiled mode
  TEXTURE_WRAP_CLAMP = 1 # Clamps texture to edge pixel in tiled mode
  TEXTURE_WRAP_MIRROR_REPEAT = 2 # Mirrors and repeats the texture in tiled mode
  TEXTURE_WRAP_MIRROR_CLAMP = 3 # Mirrors and clamps to border the texture in tiled mode
  CUBEMAP_LAYOUT_AUTO_DETECT = 0 # Automatically detect layout type
  CUBEMAP_LAYOUT_LINE_VERTICAL = 1 # Layout is defined by a vertical line with faces
  CUBEMAP_LAYOUT_LINE_HORIZONTAL = 2 # Layout is defined by an horizontal line with faces
  CUBEMAP_LAYOUT_CROSS_THREE_BY_FOUR = 3 # Layout is defined by a 3x4 cross with cubemap faces
  CUBEMAP_LAYOUT_CROSS_FOUR_BY_THREE = 4 # Layout is defined by a 4x3 cross with cubemap faces
  CUBEMAP_LAYOUT_PANORAMA = 5 # Layout is defined by a panorama image (equirectangular map)
  FONT_DEFAULT = 0 # Default font generation, anti-aliased
  FONT_BITMAP = 1 # Bitmap font generation, no anti-aliasing
  FONT_SDF = 2 # SDF font generation, requires external shader
  BLEND_ALPHA = 0 # Blend textures considering alpha (default)
  BLEND_ADDITIVE = 1 # Blend textures adding colors
  BLEND_MULTIPLIED = 2 # Blend textures multiplying colors
  BLEND_ADD_COLORS = 3 # Blend textures adding colors (alternative)
  BLEND_SUBTRACT_COLORS = 4 # Blend textures subtracting colors (alternative)
  BLEND_ALPHA_PREMULTIPLY = 5 # Blend premultiplied textures considering alpha
  BLEND_CUSTOM = 6 # Blend textures using custom src/dst factors (use rlSetBlendFactors())
  BLEND_CUSTOM_SEPARATE = 7 # Blend textures using custom rgb/alpha separate src/dst factors (use rlSetBlendFactorsSeparate())
  GESTURE_NONE = 0 # No gesture
  GESTURE_TAP = 1 # Tap gesture
  GESTURE_DOUBLETAP = 2 # Double tap gesture
  GESTURE_HOLD = 4 # Hold gesture
  GESTURE_DRAG = 8 # Drag gesture
  GESTURE_SWIPE_RIGHT = 16 # Swipe right gesture
  GESTURE_SWIPE_LEFT = 32 # Swipe left gesture
  GESTURE_SWIPE_UP = 64 # Swipe up gesture
  GESTURE_SWIPE_DOWN = 128 # Swipe down gesture
  GESTURE_PINCH_IN = 256 # Pinch in gesture
  GESTURE_PINCH_OUT = 512 # Pinch out gesture
  CAMERA_CUSTOM = 0 # Custom camera
  CAMERA_FREE = 1 # Free camera
  CAMERA_ORBITAL = 2 # Orbital camera
  CAMERA_FIRST_PERSON = 3 # First person camera
  CAMERA_THIRD_PERSON = 4 # Third person camera
  CAMERA_PERSPECTIVE = 0 # Perspective projection
  CAMERA_ORTHOGRAPHIC = 1 # Orthographic projection
  NPATCH_NINE_PATCH = 0 # Npatch layout: 3x3 tiles
  NPATCH_THREE_PATCH_VERTICAL = 1 # Npatch layout: 1x3 tiles
  NPATCH_THREE_PATCH_HORIZONTAL = 2 # Npatch layout: 3x1 tiles

  # Typedef

  typedef :int, :ConfigFlags
  typedef :int, :TraceLogLevel
  typedef :int, :KeyboardKey
  typedef :int, :MouseButton
  typedef :int, :MouseCursor
  typedef :int, :GamepadButton
  typedef :int, :GamepadAxis
  typedef :int, :MaterialMapIndex
  typedef :int, :ShaderLocationIndex
  typedef :int, :ShaderUniformDataType
  typedef :int, :ShaderAttributeDataType
  typedef :int, :PixelFormat
  typedef :int, :TextureFilter
  typedef :int, :TextureWrap
  typedef :int, :CubemapLayout
  typedef :int, :FontType
  typedef :int, :BlendMode
  typedef :int, :Gesture
  typedef :int, :CameraMode
  typedef :int, :CameraProjection
  typedef :int, :NPatchLayout
  callback :TraceLogCallback, [:int, :pointer, :int], :void
  callback :LoadFileDataCallback, [:pointer, :pointer], :pointer
  callback :SaveFileDataCallback, [:pointer, :pointer, :uint], :bool
  callback :LoadFileTextCallback, [:pointer], :pointer
  callback :SaveFileTextCallback, [:pointer, :pointer], :bool
  callback :AudioCallback, [:pointer, :uint], :void

  # Struct

  # Vector2, 2 components
  class Vector2 < FFI::Struct
    layout(
      :x, :float, # Vector x component
      :y, :float, # Vector y component
    )
  end

  # Vector3, 3 components
  class Vector3 < FFI::Struct
    layout(
      :x, :float, # Vector x component
      :y, :float, # Vector y component
      :z, :float, # Vector z component
    )
  end

  # Vector4, 4 components
  class Vector4 < FFI::Struct
    layout(
      :x, :float, # Vector x component
      :y, :float, # Vector y component
      :z, :float, # Vector z component
      :w, :float, # Vector w component
    )
  end

  Quaternion = Vector4

  # Matrix, 4x4 components, column major, OpenGL style, right handed
  class Matrix < FFI::Struct
    layout(
      :m0, :float, # Matrix first row (4 components)
      :m4, :float, # Matrix first row (4 components)
      :m8, :float, # Matrix first row (4 components)
      :m12, :float, # Matrix first row (4 components)
      :m1, :float, # Matrix second row (4 components)
      :m5, :float, # Matrix second row (4 components)
      :m9, :float, # Matrix second row (4 components)
      :m13, :float, # Matrix second row (4 components)
      :m2, :float, # Matrix third row (4 components)
      :m6, :float, # Matrix third row (4 components)
      :m10, :float, # Matrix third row (4 components)
      :m14, :float, # Matrix third row (4 components)
      :m3, :float, # Matrix fourth row (4 components)
      :m7, :float, # Matrix fourth row (4 components)
      :m11, :float, # Matrix fourth row (4 components)
      :m15, :float, # Matrix fourth row (4 components)
    )
  end

  # Color, 4 components, R8G8B8A8 (32bit)
  class Color < FFI::Struct
    layout(
      :r, :uchar, # Color red value
      :g, :uchar, # Color green value
      :b, :uchar, # Color blue value
      :a, :uchar, # Color alpha value
    )
  end

  # Rectangle, 4 components
  class Rectangle < FFI::Struct
    layout(
      :x, :float, # Rectangle top-left corner position x
      :y, :float, # Rectangle top-left corner position y
      :width, :float, # Rectangle width
      :height, :float, # Rectangle height
    )
  end

  # Image, pixel data stored in CPU memory (RAM)
  class Image < FFI::Struct
    layout(
      :data, :pointer, # Image raw data
      :width, :int, # Image base width
      :height, :int, # Image base height
      :mipmaps, :int, # Mipmap levels, 1 by default
      :format, :int, # Data format (PixelFormat type)
    )
  end

  # Texture, tex data stored in GPU memory (VRAM)
  class Texture < FFI::Struct
    layout(
      :id, :uint, # OpenGL texture id
      :width, :int, # Texture base width
      :height, :int, # Texture base height
      :mipmaps, :int, # Mipmap levels, 1 by default
      :format, :int, # Data format (PixelFormat type)
    )
  end

  Texture2D = Texture
  TextureCubemap = Texture

  # RenderTexture, fbo for texture rendering
  class RenderTexture < FFI::Struct
    layout(
      :id, :uint, # OpenGL framebuffer object id
      :texture, Texture, # Color buffer attachment texture
      :depth, Texture, # Depth buffer attachment texture
    )
  end

  RenderTexture2D = RenderTexture

  # NPatchInfo, n-patch layout info
  class NPatchInfo < FFI::Struct
    layout(
      :source, Rectangle, # Texture source rectangle
      :left, :int, # Left border offset
      :top, :int, # Top border offset
      :right, :int, # Right border offset
      :bottom, :int, # Bottom border offset
      :layout, :int, # Layout of the n-patch: 3x3, 1x3 or 3x1
    )
  end

  # GlyphInfo, font characters glyphs info
  class GlyphInfo < FFI::Struct
    layout(
      :value, :int, # Character value (Unicode)
      :offsetX, :int, # Character offset X when drawing
      :offsetY, :int, # Character offset Y when drawing
      :advanceX, :int, # Character advance position X
      :image, Image, # Character image data
    )
  end

  # Font, font texture and GlyphInfo array data
  class Font < FFI::Struct
    layout(
      :baseSize, :int, # Base size (default chars height)
      :glyphCount, :int, # Number of glyph characters
      :glyphPadding, :int, # Padding around the glyph characters
      :texture, Texture2D, # Texture atlas containing the glyphs
      :recs, :pointer, # Rectangles in texture for the glyphs
      :glyphs, :pointer, # Glyphs info data
    )
  end

  # Camera, defines position/orientation in 3d space
  class Camera3D < FFI::Struct
    layout(
      :position, Vector3, # Camera position
      :target, Vector3, # Camera target it looks-at
      :up, Vector3, # Camera up vector (rotation over its axis)
      :fovy, :float, # Camera field-of-view aperture in Y (degrees) in perspective, used as near plane width in orthographic
      :projection, :int, # Camera projection: CAMERA_PERSPECTIVE or CAMERA_ORTHOGRAPHIC
    )
  end

  Camera = Camera3D

  # Camera2D, defines position/orientation in 2d space
  class Camera2D < FFI::Struct
    layout(
      :offset, Vector2, # Camera offset (displacement from target)
      :target, Vector2, # Camera target (rotation and zoom origin)
      :rotation, :float, # Camera rotation in degrees
      :zoom, :float, # Camera zoom (scaling), should be 1.0f by default
    )
  end

  # Mesh, vertex data and vao/vbo
  class Mesh < FFI::Struct
    layout(
      :vertexCount, :int, # Number of vertices stored in arrays
      :triangleCount, :int, # Number of triangles stored (indexed or not)
      :vertices, :pointer, # Vertex position (XYZ - 3 components per vertex) (shader-location = 0)
      :texcoords, :pointer, # Vertex texture coordinates (UV - 2 components per vertex) (shader-location = 1)
      :texcoords2, :pointer, # Vertex texture second coordinates (UV - 2 components per vertex) (shader-location = 5)
      :normals, :pointer, # Vertex normals (XYZ - 3 components per vertex) (shader-location = 2)
      :tangents, :pointer, # Vertex tangents (XYZW - 4 components per vertex) (shader-location = 4)
      :colors, :pointer, # Vertex colors (RGBA - 4 components per vertex) (shader-location = 3)
      :indices, :pointer, # Vertex indices (in case vertex data comes indexed)
      :animVertices, :pointer, # Animated vertex positions (after bones transformations)
      :animNormals, :pointer, # Animated normals (after bones transformations)
      :boneIds, :pointer, # Vertex bone ids, max 255 bone ids, up to 4 bones influence by vertex (skinning)
      :boneWeights, :pointer, # Vertex bone weight, up to 4 bones influence by vertex (skinning)
      :vaoId, :uint, # OpenGL Vertex Array Object id
      :vboId, :pointer, # OpenGL Vertex Buffer Objects id (default vertex data)
    )
  end

  # Shader
  class Shader < FFI::Struct
    layout(
      :id, :uint, # Shader program id
      :locs, :pointer, # Shader locations array (RL_MAX_SHADER_LOCATIONS)
    )
  end

  # MaterialMap
  class MaterialMap < FFI::Struct
    layout(
      :texture, Texture2D, # Material map texture
      :color, Color, # Material map color
      :value, :float, # Material map value
    )
  end

  # Material, includes shader and maps
  class Material < FFI::Struct
    layout(
      :shader, Shader, # Material shader
      :maps, :pointer, # Material maps array (MAX_MATERIAL_MAPS)
      :params, [:float, 4], # Material generic parameters (if required)
    )
  end

  # Transform, vertex transformation data
  class Transform < FFI::Struct
    layout(
      :translation, Vector3, # Translation
      :rotation, Quaternion, # Rotation
      :scale, Vector3, # Scale
    )
  end

  # Bone, skeletal animation bone
  class BoneInfo < FFI::Struct
    layout(
      :name, [:char, 32], # Bone name
      :parent, :int, # Bone parent
    )
  end

  # Model, meshes, materials and animation data
  class Model < FFI::Struct
    layout(
      :transform, Matrix, # Local transform matrix
      :meshCount, :int, # Number of meshes
      :materialCount, :int, # Number of materials
      :meshes, :pointer, # Meshes array
      :materials, :pointer, # Materials array
      :meshMaterial, :pointer, # Mesh material number
      :boneCount, :int, # Number of bones
      :bones, :pointer, # Bones information (skeleton)
      :bindPose, :pointer, # Bones base transformation (pose)
    )
  end

  # ModelAnimation
  class ModelAnimation < FFI::Struct
    layout(
      :boneCount, :int, # Number of bones
      :frameCount, :int, # Number of animation frames
      :bones, :pointer, # Bones information (skeleton)
      :framePoses, :pointer, # Poses array by frame
    )
  end

  # Ray, ray for raycasting
  class Ray < FFI::Struct
    layout(
      :position, Vector3, # Ray position (origin)
      :direction, Vector3, # Ray direction
    )
  end

  # RayCollision, ray hit information
  class RayCollision < FFI::Struct
    layout(
      :hit, :bool, # Did the ray hit something?
      :distance, :float, # Distance to nearest hit
      :point, Vector3, # Point of nearest hit
      :normal, Vector3, # Surface normal of hit
    )
  end

  # BoundingBox
  class BoundingBox < FFI::Struct
    layout(
      :min, Vector3, # Minimum vertex box-corner
      :max, Vector3, # Maximum vertex box-corner
    )
  end

  # Wave, audio wave data
  class Wave < FFI::Struct
    layout(
      :frameCount, :uint, # Total number of frames (considering channels)
      :sampleRate, :uint, # Frequency (samples per second)
      :sampleSize, :uint, # Bit depth (bits per sample): 8, 16, 32 (24 not supported)
      :channels, :uint, # Number of channels (1-mono, 2-stereo, ...)
      :data, :pointer, # Buffer data pointer
    )
  end

  # AudioStream, custom audio stream
  class AudioStream < FFI::Struct
    layout(
      :buffer, :pointer, # Pointer to internal data used by the audio system
      :processor, :pointer, # Pointer to internal data processor, useful for audio effects
      :sampleRate, :uint, # Frequency (samples per second)
      :sampleSize, :uint, # Bit depth (bits per sample): 8, 16, 32 (24 not supported)
      :channels, :uint, # Number of channels (1-mono, 2-stereo, ...)
    )
  end

  # Sound
  class Sound < FFI::Struct
    layout(
      :stream, AudioStream, # Audio stream
      :frameCount, :uint, # Total number of frames (considering channels)
    )
  end

  # Music, audio stream, anything longer than ~10 seconds should be streamed
  class Music < FFI::Struct
    layout(
      :stream, AudioStream, # Audio stream
      :frameCount, :uint, # Total number of frames (considering channels)
      :looping, :bool, # Music looping enable
      :ctxType, :int, # Type of music context (audio filetype)
      :ctxData, :pointer, # Audio context data, depends on type
    )
  end

  # VrDeviceInfo, Head-Mounted-Display device parameters
  class VrDeviceInfo < FFI::Struct
    layout(
      :hResolution, :int, # Horizontal resolution in pixels
      :vResolution, :int, # Vertical resolution in pixels
      :hScreenSize, :float, # Horizontal size in meters
      :vScreenSize, :float, # Vertical size in meters
      :vScreenCenter, :float, # Screen center in meters
      :eyeToScreenDistance, :float, # Distance between eye and display in meters
      :lensSeparationDistance, :float, # Lens separation distance in meters
      :interpupillaryDistance, :float, # IPD (distance between pupils) in meters
      :lensDistortionValues, [:float, 4], # Lens distortion constant parameters
      :chromaAbCorrection, [:float, 4], # Chromatic aberration correction parameters
    )
  end

  # VrStereoConfig, VR stereo rendering configuration for simulator
  class VrStereoConfig < FFI::Struct
    layout(
      :projection, [Matrix, 2], # VR projection matrices (per eye)
      :viewOffset, [Matrix, 2], # VR view offset matrices (per eye)
      :leftLensCenter, [:float, 2], # VR left lens center
      :rightLensCenter, [:float, 2], # VR right lens center
      :leftScreenCenter, [:float, 2], # VR left screen center
      :rightScreenCenter, [:float, 2], # VR right screen center
      :scale, [:float, 2], # VR distortion scale
      :scaleIn, [:float, 2], # VR distortion scale in
    )
  end

  # File path list
  class FilePathList < FFI::Struct
    layout(
      :capacity, :uint, # Filepaths max entries
      :count, :uint, # Filepaths entries count
      :paths, :pointer, # Filepaths entries
    )
  end


  # Function

  def DrawModelEx(model, position, rotationAxis, rotationAngle, scale, tint)
    # [TODO] Fix matrix copy
    # - In C, DrawModelEx uses the whole copy of `model` on stack, which will never affect the content of original `model`.
    #   But Ruby FFI seems to pass the reference of `model` to DrawModelEx, which results in transform accumulation (e.g.:`model` get rotated by `rotationAngle` around `rotationAxis` every frame).
    #   So here I copy the transform into `mtx_clone` and copy back this to the original after finished calling DrawModelEx.
    # - Other DrawXXX members (DrawModel, DrawModelWires, DrawModelWiresEx) are free from this problem.
    #   - They call DrawModelEx in C layer, which will use the copy of `model` on stack.
    mtx_clone = model[:transform].clone
    rbDrawModelEx(model, position, rotationAxis, rotationAngle, scale, tint)
    model[:transform] = mtx_clone
  end

  def self.setup_raylib_symbols(output_error = false)
    entries = [
      [:InitWindow, :InitWindow, [:int, :int, :pointer], :void],
      [:WindowShouldClose, :WindowShouldClose, [], :bool],
      [:CloseWindow, :CloseWindow, [], :void],
      [:IsWindowReady, :IsWindowReady, [], :bool],
      [:IsWindowFullscreen, :IsWindowFullscreen, [], :bool],
      [:IsWindowHidden, :IsWindowHidden, [], :bool],
      [:IsWindowMinimized, :IsWindowMinimized, [], :bool],
      [:IsWindowMaximized, :IsWindowMaximized, [], :bool],
      [:IsWindowFocused, :IsWindowFocused, [], :bool],
      [:IsWindowResized, :IsWindowResized, [], :bool],
      [:IsWindowState, :IsWindowState, [:uint], :bool],
      [:SetWindowState, :SetWindowState, [:uint], :void],
      [:ClearWindowState, :ClearWindowState, [:uint], :void],
      [:ToggleFullscreen, :ToggleFullscreen, [], :void],
      [:MaximizeWindow, :MaximizeWindow, [], :void],
      [:MinimizeWindow, :MinimizeWindow, [], :void],
      [:RestoreWindow, :RestoreWindow, [], :void],
      [:SetWindowIcon, :SetWindowIcon, [Image.by_value], :void],
      [:SetWindowTitle, :SetWindowTitle, [:pointer], :void],
      [:SetWindowPosition, :SetWindowPosition, [:int, :int], :void],
      [:SetWindowMonitor, :SetWindowMonitor, [:int], :void],
      [:SetWindowMinSize, :SetWindowMinSize, [:int, :int], :void],
      [:SetWindowSize, :SetWindowSize, [:int, :int], :void],
      [:SetWindowOpacity, :SetWindowOpacity, [:float], :void],
      [:GetWindowHandle, :GetWindowHandle, [], :pointer],
      [:GetScreenWidth, :GetScreenWidth, [], :int],
      [:GetScreenHeight, :GetScreenHeight, [], :int],
      [:GetRenderWidth, :GetRenderWidth, [], :int],
      [:GetRenderHeight, :GetRenderHeight, [], :int],
      [:GetMonitorCount, :GetMonitorCount, [], :int],
      [:GetCurrentMonitor, :GetCurrentMonitor, [], :int],
      [:GetMonitorPosition, :GetMonitorPosition, [:int], Vector2.by_value],
      [:GetMonitorWidth, :GetMonitorWidth, [:int], :int],
      [:GetMonitorHeight, :GetMonitorHeight, [:int], :int],
      [:GetMonitorPhysicalWidth, :GetMonitorPhysicalWidth, [:int], :int],
      [:GetMonitorPhysicalHeight, :GetMonitorPhysicalHeight, [:int], :int],
      [:GetMonitorRefreshRate, :GetMonitorRefreshRate, [:int], :int],
      [:GetWindowPosition, :GetWindowPosition, [], Vector2.by_value],
      [:GetWindowScaleDPI, :GetWindowScaleDPI, [], Vector2.by_value],
      [:GetMonitorName, :GetMonitorName, [:int], :pointer],
      [:SetClipboardText, :SetClipboardText, [:pointer], :void],
      [:GetClipboardText, :GetClipboardText, [], :pointer],
      [:EnableEventWaiting, :EnableEventWaiting, [], :void],
      [:DisableEventWaiting, :DisableEventWaiting, [], :void],
      [:SwapScreenBuffer, :SwapScreenBuffer, [], :void],
      [:PollInputEvents, :PollInputEvents, [], :void],
      [:WaitTime, :WaitTime, [:double], :void],
      [:ShowCursor, :ShowCursor, [], :void],
      [:HideCursor, :HideCursor, [], :void],
      [:IsCursorHidden, :IsCursorHidden, [], :bool],
      [:EnableCursor, :EnableCursor, [], :void],
      [:DisableCursor, :DisableCursor, [], :void],
      [:IsCursorOnScreen, :IsCursorOnScreen, [], :bool],
      [:ClearBackground, :ClearBackground, [Color.by_value], :void],
      [:BeginDrawing, :BeginDrawing, [], :void],
      [:EndDrawing, :EndDrawing, [], :void],
      [:BeginMode2D, :BeginMode2D, [Camera2D.by_value], :void],
      [:EndMode2D, :EndMode2D, [], :void],
      [:BeginMode3D, :BeginMode3D, [Camera3D.by_value], :void],
      [:EndMode3D, :EndMode3D, [], :void],
      [:BeginTextureMode, :BeginTextureMode, [RenderTexture2D.by_value], :void],
      [:EndTextureMode, :EndTextureMode, [], :void],
      [:BeginShaderMode, :BeginShaderMode, [Shader.by_value], :void],
      [:EndShaderMode, :EndShaderMode, [], :void],
      [:BeginBlendMode, :BeginBlendMode, [:int], :void],
      [:EndBlendMode, :EndBlendMode, [], :void],
      [:BeginScissorMode, :BeginScissorMode, [:int, :int, :int, :int], :void],
      [:EndScissorMode, :EndScissorMode, [], :void],
      [:BeginVrStereoMode, :BeginVrStereoMode, [VrStereoConfig.by_value], :void],
      [:EndVrStereoMode, :EndVrStereoMode, [], :void],
      [:LoadVrStereoConfig, :LoadVrStereoConfig, [VrDeviceInfo.by_value], VrStereoConfig.by_value],
      [:UnloadVrStereoConfig, :UnloadVrStereoConfig, [VrStereoConfig.by_value], :void],
      [:LoadShader, :LoadShader, [:pointer, :pointer], Shader.by_value],
      [:LoadShaderFromMemory, :LoadShaderFromMemory, [:pointer, :pointer], Shader.by_value],
      [:GetShaderLocation, :GetShaderLocation, [Shader.by_value, :pointer], :int],
      [:GetShaderLocationAttrib, :GetShaderLocationAttrib, [Shader.by_value, :pointer], :int],
      [:SetShaderValue, :SetShaderValue, [Shader.by_value, :int, :pointer, :int], :void],
      [:SetShaderValueV, :SetShaderValueV, [Shader.by_value, :int, :pointer, :int, :int], :void],
      [:SetShaderValueMatrix, :SetShaderValueMatrix, [Shader.by_value, :int, Matrix.by_value], :void],
      [:SetShaderValueTexture, :SetShaderValueTexture, [Shader.by_value, :int, Texture2D.by_value], :void],
      [:UnloadShader, :UnloadShader, [Shader.by_value], :void],
      [:GetMouseRay, :GetMouseRay, [Vector2.by_value, Camera.by_value], Ray.by_value],
      [:GetCameraMatrix, :GetCameraMatrix, [Camera.by_value], Matrix.by_value],
      [:GetCameraMatrix2D, :GetCameraMatrix2D, [Camera2D.by_value], Matrix.by_value],
      [:GetWorldToScreen, :GetWorldToScreen, [Vector3.by_value, Camera.by_value], Vector2.by_value],
      [:GetScreenToWorld2D, :GetScreenToWorld2D, [Vector2.by_value, Camera2D.by_value], Vector2.by_value],
      [:GetWorldToScreenEx, :GetWorldToScreenEx, [Vector3.by_value, Camera.by_value, :int, :int], Vector2.by_value],
      [:GetWorldToScreen2D, :GetWorldToScreen2D, [Vector2.by_value, Camera2D.by_value], Vector2.by_value],
      [:SetTargetFPS, :SetTargetFPS, [:int], :void],
      [:GetFPS, :GetFPS, [], :int],
      [:GetFrameTime, :GetFrameTime, [], :float],
      [:GetTime, :GetTime, [], :double],
      [:GetRandomValue, :GetRandomValue, [:int, :int], :int],
      [:SetRandomSeed, :SetRandomSeed, [:uint], :void],
      [:TakeScreenshot, :TakeScreenshot, [:pointer], :void],
      [:SetConfigFlags, :SetConfigFlags, [:uint], :void],
      [:TraceLog, :TraceLog, [:int, :pointer, :varargs], :void],
      [:SetTraceLogLevel, :SetTraceLogLevel, [:int], :void],
      [:MemAlloc, :MemAlloc, [:uint], :pointer],
      [:MemRealloc, :MemRealloc, [:pointer, :uint], :pointer],
      [:MemFree, :MemFree, [:pointer], :void],
      [:OpenURL, :OpenURL, [:pointer], :void],
      [:SetTraceLogCallback, :SetTraceLogCallback, [:TraceLogCallback], :void],
      [:SetLoadFileDataCallback, :SetLoadFileDataCallback, [:LoadFileDataCallback], :void],
      [:SetSaveFileDataCallback, :SetSaveFileDataCallback, [:SaveFileDataCallback], :void],
      [:SetLoadFileTextCallback, :SetLoadFileTextCallback, [:LoadFileTextCallback], :void],
      [:SetSaveFileTextCallback, :SetSaveFileTextCallback, [:SaveFileTextCallback], :void],
      [:LoadFileData, :LoadFileData, [:pointer, :pointer], :pointer],
      [:UnloadFileData, :UnloadFileData, [:pointer], :void],
      [:SaveFileData, :SaveFileData, [:pointer, :pointer, :uint], :bool],
      [:ExportDataAsCode, :ExportDataAsCode, [:pointer, :uint, :pointer], :bool],
      [:LoadFileText, :LoadFileText, [:pointer], :pointer],
      [:UnloadFileText, :UnloadFileText, [:pointer], :void],
      [:SaveFileText, :SaveFileText, [:pointer, :pointer], :bool],
      [:FileExists, :FileExists, [:pointer], :bool],
      [:DirectoryExists, :DirectoryExists, [:pointer], :bool],
      [:IsFileExtension, :IsFileExtension, [:pointer, :pointer], :bool],
      [:GetFileLength, :GetFileLength, [:pointer], :int],
      [:GetFileExtension, :GetFileExtension, [:pointer], :pointer],
      [:GetFileName, :GetFileName, [:pointer], :pointer],
      [:GetFileNameWithoutExt, :GetFileNameWithoutExt, [:pointer], :pointer],
      [:GetDirectoryPath, :GetDirectoryPath, [:pointer], :pointer],
      [:GetPrevDirectoryPath, :GetPrevDirectoryPath, [:pointer], :pointer],
      [:GetWorkingDirectory, :GetWorkingDirectory, [], :pointer],
      [:GetApplicationDirectory, :GetApplicationDirectory, [], :pointer],
      [:ChangeDirectory, :ChangeDirectory, [:pointer], :bool],
      [:IsPathFile, :IsPathFile, [:pointer], :bool],
      [:LoadDirectoryFiles, :LoadDirectoryFiles, [:pointer], FilePathList.by_value],
      [:LoadDirectoryFilesEx, :LoadDirectoryFilesEx, [:pointer, :pointer, :bool], FilePathList.by_value],
      [:UnloadDirectoryFiles, :UnloadDirectoryFiles, [FilePathList.by_value], :void],
      [:IsFileDropped, :IsFileDropped, [], :bool],
      [:LoadDroppedFiles, :LoadDroppedFiles, [], FilePathList.by_value],
      [:UnloadDroppedFiles, :UnloadDroppedFiles, [FilePathList.by_value], :void],
      [:GetFileModTime, :GetFileModTime, [:pointer], :long],
      [:CompressData, :CompressData, [:pointer, :int, :pointer], :pointer],
      [:DecompressData, :DecompressData, [:pointer, :int, :pointer], :pointer],
      [:EncodeDataBase64, :EncodeDataBase64, [:pointer, :int, :pointer], :pointer],
      [:DecodeDataBase64, :DecodeDataBase64, [:pointer, :pointer], :pointer],
      [:IsKeyPressed, :IsKeyPressed, [:int], :bool],
      [:IsKeyDown, :IsKeyDown, [:int], :bool],
      [:IsKeyReleased, :IsKeyReleased, [:int], :bool],
      [:IsKeyUp, :IsKeyUp, [:int], :bool],
      [:SetExitKey, :SetExitKey, [:int], :void],
      [:GetKeyPressed, :GetKeyPressed, [], :int],
      [:GetCharPressed, :GetCharPressed, [], :int],
      [:IsGamepadAvailable, :IsGamepadAvailable, [:int], :bool],
      [:GetGamepadName, :GetGamepadName, [:int], :pointer],
      [:IsGamepadButtonPressed, :IsGamepadButtonPressed, [:int, :int], :bool],
      [:IsGamepadButtonDown, :IsGamepadButtonDown, [:int, :int], :bool],
      [:IsGamepadButtonReleased, :IsGamepadButtonReleased, [:int, :int], :bool],
      [:IsGamepadButtonUp, :IsGamepadButtonUp, [:int, :int], :bool],
      [:GetGamepadButtonPressed, :GetGamepadButtonPressed, [], :int],
      [:GetGamepadAxisCount, :GetGamepadAxisCount, [:int], :int],
      [:GetGamepadAxisMovement, :GetGamepadAxisMovement, [:int, :int], :float],
      [:SetGamepadMappings, :SetGamepadMappings, [:pointer], :int],
      [:IsMouseButtonPressed, :IsMouseButtonPressed, [:int], :bool],
      [:IsMouseButtonDown, :IsMouseButtonDown, [:int], :bool],
      [:IsMouseButtonReleased, :IsMouseButtonReleased, [:int], :bool],
      [:IsMouseButtonUp, :IsMouseButtonUp, [:int], :bool],
      [:GetMouseX, :GetMouseX, [], :int],
      [:GetMouseY, :GetMouseY, [], :int],
      [:GetMousePosition, :GetMousePosition, [], Vector2.by_value],
      [:GetMouseDelta, :GetMouseDelta, [], Vector2.by_value],
      [:SetMousePosition, :SetMousePosition, [:int, :int], :void],
      [:SetMouseOffset, :SetMouseOffset, [:int, :int], :void],
      [:SetMouseScale, :SetMouseScale, [:float, :float], :void],
      [:GetMouseWheelMove, :GetMouseWheelMove, [], :float],
      [:GetMouseWheelMoveV, :GetMouseWheelMoveV, [], Vector2.by_value],
      [:SetMouseCursor, :SetMouseCursor, [:int], :void],
      [:GetTouchX, :GetTouchX, [], :int],
      [:GetTouchY, :GetTouchY, [], :int],
      [:GetTouchPosition, :GetTouchPosition, [:int], Vector2.by_value],
      [:GetTouchPointId, :GetTouchPointId, [:int], :int],
      [:GetTouchPointCount, :GetTouchPointCount, [], :int],
      [:SetGesturesEnabled, :SetGesturesEnabled, [:uint], :void],
      [:IsGestureDetected, :IsGestureDetected, [:int], :bool],
      [:GetGestureDetected, :GetGestureDetected, [], :int],
      [:GetGestureHoldDuration, :GetGestureHoldDuration, [], :float],
      [:GetGestureDragVector, :GetGestureDragVector, [], Vector2.by_value],
      [:GetGestureDragAngle, :GetGestureDragAngle, [], :float],
      [:GetGesturePinchVector, :GetGesturePinchVector, [], Vector2.by_value],
      [:GetGesturePinchAngle, :GetGesturePinchAngle, [], :float],
      [:SetCameraMode, :SetCameraMode, [Camera.by_value, :int], :void],
      [:UpdateCamera, :UpdateCamera, [:pointer], :void],
      [:SetCameraPanControl, :SetCameraPanControl, [:int], :void],
      [:SetCameraAltControl, :SetCameraAltControl, [:int], :void],
      [:SetCameraSmoothZoomControl, :SetCameraSmoothZoomControl, [:int], :void],
      [:SetCameraMoveControls, :SetCameraMoveControls, [:int, :int, :int, :int, :int, :int], :void],
      [:SetShapesTexture, :SetShapesTexture, [Texture2D.by_value, Rectangle.by_value], :void],
      [:DrawPixel, :DrawPixel, [:int, :int, Color.by_value], :void],
      [:DrawPixelV, :DrawPixelV, [Vector2.by_value, Color.by_value], :void],
      [:DrawLine, :DrawLine, [:int, :int, :int, :int, Color.by_value], :void],
      [:DrawLineV, :DrawLineV, [Vector2.by_value, Vector2.by_value, Color.by_value], :void],
      [:DrawLineEx, :DrawLineEx, [Vector2.by_value, Vector2.by_value, :float, Color.by_value], :void],
      [:DrawLineBezier, :DrawLineBezier, [Vector2.by_value, Vector2.by_value, :float, Color.by_value], :void],
      [:DrawLineBezierQuad, :DrawLineBezierQuad, [Vector2.by_value, Vector2.by_value, Vector2.by_value, :float, Color.by_value], :void],
      [:DrawLineBezierCubic, :DrawLineBezierCubic, [Vector2.by_value, Vector2.by_value, Vector2.by_value, Vector2.by_value, :float, Color.by_value], :void],
      [:DrawLineStrip, :DrawLineStrip, [:pointer, :int, Color.by_value], :void],
      [:DrawCircle, :DrawCircle, [:int, :int, :float, Color.by_value], :void],
      [:DrawCircleSector, :DrawCircleSector, [Vector2.by_value, :float, :float, :float, :int, Color.by_value], :void],
      [:DrawCircleSectorLines, :DrawCircleSectorLines, [Vector2.by_value, :float, :float, :float, :int, Color.by_value], :void],
      [:DrawCircleGradient, :DrawCircleGradient, [:int, :int, :float, Color.by_value, Color.by_value], :void],
      [:DrawCircleV, :DrawCircleV, [Vector2.by_value, :float, Color.by_value], :void],
      [:DrawCircleLines, :DrawCircleLines, [:int, :int, :float, Color.by_value], :void],
      [:DrawEllipse, :DrawEllipse, [:int, :int, :float, :float, Color.by_value], :void],
      [:DrawEllipseLines, :DrawEllipseLines, [:int, :int, :float, :float, Color.by_value], :void],
      [:DrawRing, :DrawRing, [Vector2.by_value, :float, :float, :float, :float, :int, Color.by_value], :void],
      [:DrawRingLines, :DrawRingLines, [Vector2.by_value, :float, :float, :float, :float, :int, Color.by_value], :void],
      [:DrawRectangle, :DrawRectangle, [:int, :int, :int, :int, Color.by_value], :void],
      [:DrawRectangleV, :DrawRectangleV, [Vector2.by_value, Vector2.by_value, Color.by_value], :void],
      [:DrawRectangleRec, :DrawRectangleRec, [Rectangle.by_value, Color.by_value], :void],
      [:DrawRectanglePro, :DrawRectanglePro, [Rectangle.by_value, Vector2.by_value, :float, Color.by_value], :void],
      [:DrawRectangleGradientV, :DrawRectangleGradientV, [:int, :int, :int, :int, Color.by_value, Color.by_value], :void],
      [:DrawRectangleGradientH, :DrawRectangleGradientH, [:int, :int, :int, :int, Color.by_value, Color.by_value], :void],
      [:DrawRectangleGradientEx, :DrawRectangleGradientEx, [Rectangle.by_value, Color.by_value, Color.by_value, Color.by_value, Color.by_value], :void],
      [:DrawRectangleLines, :DrawRectangleLines, [:int, :int, :int, :int, Color.by_value], :void],
      [:DrawRectangleLinesEx, :DrawRectangleLinesEx, [Rectangle.by_value, :float, Color.by_value], :void],
      [:DrawRectangleRounded, :DrawRectangleRounded, [Rectangle.by_value, :float, :int, Color.by_value], :void],
      [:DrawRectangleRoundedLines, :DrawRectangleRoundedLines, [Rectangle.by_value, :float, :int, :float, Color.by_value], :void],
      [:DrawTriangle, :DrawTriangle, [Vector2.by_value, Vector2.by_value, Vector2.by_value, Color.by_value], :void],
      [:DrawTriangleLines, :DrawTriangleLines, [Vector2.by_value, Vector2.by_value, Vector2.by_value, Color.by_value], :void],
      [:DrawTriangleFan, :DrawTriangleFan, [:pointer, :int, Color.by_value], :void],
      [:DrawTriangleStrip, :DrawTriangleStrip, [:pointer, :int, Color.by_value], :void],
      [:DrawPoly, :DrawPoly, [Vector2.by_value, :int, :float, :float, Color.by_value], :void],
      [:DrawPolyLines, :DrawPolyLines, [Vector2.by_value, :int, :float, :float, Color.by_value], :void],
      [:DrawPolyLinesEx, :DrawPolyLinesEx, [Vector2.by_value, :int, :float, :float, :float, Color.by_value], :void],
      [:CheckCollisionRecs, :CheckCollisionRecs, [Rectangle.by_value, Rectangle.by_value], :bool],
      [:CheckCollisionCircles, :CheckCollisionCircles, [Vector2.by_value, :float, Vector2.by_value, :float], :bool],
      [:CheckCollisionCircleRec, :CheckCollisionCircleRec, [Vector2.by_value, :float, Rectangle.by_value], :bool],
      [:CheckCollisionPointRec, :CheckCollisionPointRec, [Vector2.by_value, Rectangle.by_value], :bool],
      [:CheckCollisionPointCircle, :CheckCollisionPointCircle, [Vector2.by_value, Vector2.by_value, :float], :bool],
      [:CheckCollisionPointTriangle, :CheckCollisionPointTriangle, [Vector2.by_value, Vector2.by_value, Vector2.by_value, Vector2.by_value], :bool],
      [:CheckCollisionPointPoly, :CheckCollisionPointPoly, [Vector2.by_value, :pointer, :int], :bool],
      [:CheckCollisionLines, :CheckCollisionLines, [Vector2.by_value, Vector2.by_value, Vector2.by_value, Vector2.by_value, :pointer], :bool],
      [:CheckCollisionPointLine, :CheckCollisionPointLine, [Vector2.by_value, Vector2.by_value, Vector2.by_value, :int], :bool],
      [:GetCollisionRec, :GetCollisionRec, [Rectangle.by_value, Rectangle.by_value], Rectangle.by_value],
      [:LoadImage, :LoadImage, [:pointer], Image.by_value],
      [:LoadImageRaw, :LoadImageRaw, [:pointer, :int, :int, :int, :int], Image.by_value],
      [:LoadImageAnim, :LoadImageAnim, [:pointer, :pointer], Image.by_value],
      [:LoadImageFromMemory, :LoadImageFromMemory, [:pointer, :pointer, :int], Image.by_value],
      [:LoadImageFromTexture, :LoadImageFromTexture, [Texture2D.by_value], Image.by_value],
      [:LoadImageFromScreen, :LoadImageFromScreen, [], Image.by_value],
      [:UnloadImage, :UnloadImage, [Image.by_value], :void],
      [:ExportImage, :ExportImage, [Image.by_value, :pointer], :bool],
      [:ExportImageAsCode, :ExportImageAsCode, [Image.by_value, :pointer], :bool],
      [:GenImageColor, :GenImageColor, [:int, :int, Color.by_value], Image.by_value],
      [:GenImageGradientV, :GenImageGradientV, [:int, :int, Color.by_value, Color.by_value], Image.by_value],
      [:GenImageGradientH, :GenImageGradientH, [:int, :int, Color.by_value, Color.by_value], Image.by_value],
      [:GenImageGradientRadial, :GenImageGradientRadial, [:int, :int, :float, Color.by_value, Color.by_value], Image.by_value],
      [:GenImageChecked, :GenImageChecked, [:int, :int, :int, :int, Color.by_value, Color.by_value], Image.by_value],
      [:GenImageWhiteNoise, :GenImageWhiteNoise, [:int, :int, :float], Image.by_value],
      [:GenImagePerlinNoise, :GenImagePerlinNoise, [:int, :int, :int, :int, :float], Image.by_value],
      [:GenImageCellular, :GenImageCellular, [:int, :int, :int], Image.by_value],
      [:GenImageText, :GenImageText, [:int, :int, :pointer], Image.by_value],
      [:ImageCopy, :ImageCopy, [Image.by_value], Image.by_value],
      [:ImageFromImage, :ImageFromImage, [Image.by_value, Rectangle.by_value], Image.by_value],
      [:ImageText, :ImageText, [:pointer, :int, Color.by_value], Image.by_value],
      [:ImageTextEx, :ImageTextEx, [Font.by_value, :pointer, :float, :float, Color.by_value], Image.by_value],
      [:ImageFormat, :ImageFormat, [:pointer, :int], :void],
      [:ImageToPOT, :ImageToPOT, [:pointer, Color.by_value], :void],
      [:ImageCrop, :ImageCrop, [:pointer, Rectangle.by_value], :void],
      [:ImageAlphaCrop, :ImageAlphaCrop, [:pointer, :float], :void],
      [:ImageAlphaClear, :ImageAlphaClear, [:pointer, Color.by_value, :float], :void],
      [:ImageAlphaMask, :ImageAlphaMask, [:pointer, Image.by_value], :void],
      [:ImageAlphaPremultiply, :ImageAlphaPremultiply, [:pointer], :void],
      [:ImageBlurGaussian, :ImageBlurGaussian, [:pointer, :int], :void],
      [:ImageResize, :ImageResize, [:pointer, :int, :int], :void],
      [:ImageResizeNN, :ImageResizeNN, [:pointer, :int, :int], :void],
      [:ImageResizeCanvas, :ImageResizeCanvas, [:pointer, :int, :int, :int, :int, Color.by_value], :void],
      [:ImageMipmaps, :ImageMipmaps, [:pointer], :void],
      [:ImageDither, :ImageDither, [:pointer, :int, :int, :int, :int], :void],
      [:ImageFlipVertical, :ImageFlipVertical, [:pointer], :void],
      [:ImageFlipHorizontal, :ImageFlipHorizontal, [:pointer], :void],
      [:ImageRotateCW, :ImageRotateCW, [:pointer], :void],
      [:ImageRotateCCW, :ImageRotateCCW, [:pointer], :void],
      [:ImageColorTint, :ImageColorTint, [:pointer, Color.by_value], :void],
      [:ImageColorInvert, :ImageColorInvert, [:pointer], :void],
      [:ImageColorGrayscale, :ImageColorGrayscale, [:pointer], :void],
      [:ImageColorContrast, :ImageColorContrast, [:pointer, :float], :void],
      [:ImageColorBrightness, :ImageColorBrightness, [:pointer, :int], :void],
      [:ImageColorReplace, :ImageColorReplace, [:pointer, Color.by_value, Color.by_value], :void],
      [:LoadImageColors, :LoadImageColors, [Image.by_value], :pointer],
      [:LoadImagePalette, :LoadImagePalette, [Image.by_value, :int, :pointer], :pointer],
      [:UnloadImageColors, :UnloadImageColors, [:pointer], :void],
      [:UnloadImagePalette, :UnloadImagePalette, [:pointer], :void],
      [:GetImageAlphaBorder, :GetImageAlphaBorder, [Image.by_value, :float], Rectangle.by_value],
      [:GetImageColor, :GetImageColor, [Image.by_value, :int, :int], Color.by_value],
      [:ImageClearBackground, :ImageClearBackground, [:pointer, Color.by_value], :void],
      [:ImageDrawPixel, :ImageDrawPixel, [:pointer, :int, :int, Color.by_value], :void],
      [:ImageDrawPixelV, :ImageDrawPixelV, [:pointer, Vector2.by_value, Color.by_value], :void],
      [:ImageDrawLine, :ImageDrawLine, [:pointer, :int, :int, :int, :int, Color.by_value], :void],
      [:ImageDrawLineV, :ImageDrawLineV, [:pointer, Vector2.by_value, Vector2.by_value, Color.by_value], :void],
      [:ImageDrawCircle, :ImageDrawCircle, [:pointer, :int, :int, :int, Color.by_value], :void],
      [:ImageDrawCircleV, :ImageDrawCircleV, [:pointer, Vector2.by_value, :int, Color.by_value], :void],
      [:ImageDrawCircleLines, :ImageDrawCircleLines, [:pointer, :int, :int, :int, Color.by_value], :void],
      [:ImageDrawCircleLinesV, :ImageDrawCircleLinesV, [:pointer, Vector2.by_value, :int, Color.by_value], :void],
      [:ImageDrawRectangle, :ImageDrawRectangle, [:pointer, :int, :int, :int, :int, Color.by_value], :void],
      [:ImageDrawRectangleV, :ImageDrawRectangleV, [:pointer, Vector2.by_value, Vector2.by_value, Color.by_value], :void],
      [:ImageDrawRectangleRec, :ImageDrawRectangleRec, [:pointer, Rectangle.by_value, Color.by_value], :void],
      [:ImageDrawRectangleLines, :ImageDrawRectangleLines, [:pointer, Rectangle.by_value, :int, Color.by_value], :void],
      [:ImageDraw, :ImageDraw, [:pointer, Image.by_value, Rectangle.by_value, Rectangle.by_value, Color.by_value], :void],
      [:ImageDrawText, :ImageDrawText, [:pointer, :pointer, :int, :int, :int, Color.by_value], :void],
      [:ImageDrawTextEx, :ImageDrawTextEx, [:pointer, Font.by_value, :pointer, Vector2.by_value, :float, :float, Color.by_value], :void],
      [:LoadTexture, :LoadTexture, [:pointer], Texture2D.by_value],
      [:LoadTextureFromImage, :LoadTextureFromImage, [Image.by_value], Texture2D.by_value],
      [:LoadTextureCubemap, :LoadTextureCubemap, [Image.by_value, :int], TextureCubemap.by_value],
      [:LoadRenderTexture, :LoadRenderTexture, [:int, :int], RenderTexture2D.by_value],
      [:UnloadTexture, :UnloadTexture, [Texture2D.by_value], :void],
      [:UnloadRenderTexture, :UnloadRenderTexture, [RenderTexture2D.by_value], :void],
      [:UpdateTexture, :UpdateTexture, [Texture2D.by_value, :pointer], :void],
      [:UpdateTextureRec, :UpdateTextureRec, [Texture2D.by_value, Rectangle.by_value, :pointer], :void],
      [:GenTextureMipmaps, :GenTextureMipmaps, [:pointer], :void],
      [:SetTextureFilter, :SetTextureFilter, [Texture2D.by_value, :int], :void],
      [:SetTextureWrap, :SetTextureWrap, [Texture2D.by_value, :int], :void],
      [:DrawTexture, :DrawTexture, [Texture2D.by_value, :int, :int, Color.by_value], :void],
      [:DrawTextureV, :DrawTextureV, [Texture2D.by_value, Vector2.by_value, Color.by_value], :void],
      [:DrawTextureEx, :DrawTextureEx, [Texture2D.by_value, Vector2.by_value, :float, :float, Color.by_value], :void],
      [:DrawTextureRec, :DrawTextureRec, [Texture2D.by_value, Rectangle.by_value, Vector2.by_value, Color.by_value], :void],
      [:DrawTexturePro, :DrawTexturePro, [Texture2D.by_value, Rectangle.by_value, Rectangle.by_value, Vector2.by_value, :float, Color.by_value], :void],
      [:DrawTextureNPatch, :DrawTextureNPatch, [Texture2D.by_value, NPatchInfo.by_value, Rectangle.by_value, Vector2.by_value, :float, Color.by_value], :void],
      [:Fade, :Fade, [Color.by_value, :float], Color.by_value],
      [:ColorToInt, :ColorToInt, [Color.by_value], :int],
      [:ColorNormalize, :ColorNormalize, [Color.by_value], Vector4.by_value],
      [:ColorFromNormalized, :ColorFromNormalized, [Vector4.by_value], Color.by_value],
      [:ColorToHSV, :ColorToHSV, [Color.by_value], Vector3.by_value],
      [:ColorFromHSV, :ColorFromHSV, [:float, :float, :float], Color.by_value],
      [:ColorTint, :ColorTint, [Color.by_value, Color.by_value], Color.by_value],
      [:ColorBrightness, :ColorBrightness, [Color.by_value, :float], Color.by_value],
      [:ColorContrast, :ColorContrast, [Color.by_value, :float], Color.by_value],
      [:ColorAlpha, :ColorAlpha, [Color.by_value, :float], Color.by_value],
      [:ColorAlphaBlend, :ColorAlphaBlend, [Color.by_value, Color.by_value, Color.by_value], Color.by_value],
      [:GetColor, :GetColor, [:uint], Color.by_value],
      [:GetPixelColor, :GetPixelColor, [:pointer, :int], Color.by_value],
      [:SetPixelColor, :SetPixelColor, [:pointer, Color.by_value, :int], :void],
      [:GetPixelDataSize, :GetPixelDataSize, [:int, :int, :int], :int],
      [:GetFontDefault, :GetFontDefault, [], Font.by_value],
      [:LoadFont, :LoadFont, [:pointer], Font.by_value],
      [:LoadFontEx, :LoadFontEx, [:pointer, :int, :pointer, :int], Font.by_value],
      [:LoadFontFromImage, :LoadFontFromImage, [Image.by_value, Color.by_value, :int], Font.by_value],
      [:LoadFontFromMemory, :LoadFontFromMemory, [:pointer, :pointer, :int, :int, :pointer, :int], Font.by_value],
      [:LoadFontData, :LoadFontData, [:pointer, :int, :int, :pointer, :int, :int], :pointer],
      [:GenImageFontAtlas, :GenImageFontAtlas, [:pointer, :pointer, :int, :int, :int, :int], Image.by_value],
      [:UnloadFontData, :UnloadFontData, [:pointer, :int], :void],
      [:UnloadFont, :UnloadFont, [Font.by_value], :void],
      [:ExportFontAsCode, :ExportFontAsCode, [Font.by_value, :pointer], :bool],
      [:DrawFPS, :DrawFPS, [:int, :int], :void],
      [:DrawText, :DrawText, [:pointer, :int, :int, :int, Color.by_value], :void],
      [:DrawTextEx, :DrawTextEx, [Font.by_value, :pointer, Vector2.by_value, :float, :float, Color.by_value], :void],
      [:DrawTextPro, :DrawTextPro, [Font.by_value, :pointer, Vector2.by_value, Vector2.by_value, :float, :float, :float, Color.by_value], :void],
      [:DrawTextCodepoint, :DrawTextCodepoint, [Font.by_value, :int, Vector2.by_value, :float, Color.by_value], :void],
      [:DrawTextCodepoints, :DrawTextCodepoints, [Font.by_value, :pointer, :int, Vector2.by_value, :float, :float, Color.by_value], :void],
      [:MeasureText, :MeasureText, [:pointer, :int], :int],
      [:MeasureTextEx, :MeasureTextEx, [Font.by_value, :pointer, :float, :float], Vector2.by_value],
      [:GetGlyphIndex, :GetGlyphIndex, [Font.by_value, :int], :int],
      [:GetGlyphInfo, :GetGlyphInfo, [Font.by_value, :int], GlyphInfo.by_value],
      [:GetGlyphAtlasRec, :GetGlyphAtlasRec, [Font.by_value, :int], Rectangle.by_value],
      [:LoadUTF8, :LoadUTF8, [:pointer, :int], :pointer],
      [:UnloadUTF8, :UnloadUTF8, [:pointer], :void],
      [:LoadCodepoints, :LoadCodepoints, [:pointer, :pointer], :pointer],
      [:UnloadCodepoints, :UnloadCodepoints, [:pointer], :void],
      [:GetCodepointCount, :GetCodepointCount, [:pointer], :int],
      [:GetCodepoint, :GetCodepoint, [:pointer, :pointer], :int],
      [:GetCodepointNext, :GetCodepointNext, [:pointer, :pointer], :int],
      [:GetCodepointPrevious, :GetCodepointPrevious, [:pointer, :pointer], :int],
      [:CodepointToUTF8, :CodepointToUTF8, [:int, :pointer], :pointer],
      [:TextCopy, :TextCopy, [:pointer, :pointer], :int],
      [:TextIsEqual, :TextIsEqual, [:pointer, :pointer], :bool],
      [:TextLength, :TextLength, [:pointer], :uint],
      [:TextFormat, :TextFormat, [:pointer, :varargs], :pointer],
      [:TextSubtext, :TextSubtext, [:pointer, :int, :int], :pointer],
      [:TextReplace, :TextReplace, [:pointer, :pointer, :pointer], :pointer],
      [:TextInsert, :TextInsert, [:pointer, :pointer, :int], :pointer],
      [:TextJoin, :TextJoin, [:pointer, :int, :pointer], :pointer],
      [:TextSplit, :TextSplit, [:pointer, :char, :pointer], :pointer],
      [:TextAppend, :TextAppend, [:pointer, :pointer, :pointer], :void],
      [:TextFindIndex, :TextFindIndex, [:pointer, :pointer], :int],
      [:TextToUpper, :TextToUpper, [:pointer], :pointer],
      [:TextToLower, :TextToLower, [:pointer], :pointer],
      [:TextToPascal, :TextToPascal, [:pointer], :pointer],
      [:TextToInteger, :TextToInteger, [:pointer], :int],
      [:DrawLine3D, :DrawLine3D, [Vector3.by_value, Vector3.by_value, Color.by_value], :void],
      [:DrawPoint3D, :DrawPoint3D, [Vector3.by_value, Color.by_value], :void],
      [:DrawCircle3D, :DrawCircle3D, [Vector3.by_value, :float, Vector3.by_value, :float, Color.by_value], :void],
      [:DrawTriangle3D, :DrawTriangle3D, [Vector3.by_value, Vector3.by_value, Vector3.by_value, Color.by_value], :void],
      [:DrawTriangleStrip3D, :DrawTriangleStrip3D, [:pointer, :int, Color.by_value], :void],
      [:DrawCube, :DrawCube, [Vector3.by_value, :float, :float, :float, Color.by_value], :void],
      [:DrawCubeV, :DrawCubeV, [Vector3.by_value, Vector3.by_value, Color.by_value], :void],
      [:DrawCubeWires, :DrawCubeWires, [Vector3.by_value, :float, :float, :float, Color.by_value], :void],
      [:DrawCubeWiresV, :DrawCubeWiresV, [Vector3.by_value, Vector3.by_value, Color.by_value], :void],
      [:DrawSphere, :DrawSphere, [Vector3.by_value, :float, Color.by_value], :void],
      [:DrawSphereEx, :DrawSphereEx, [Vector3.by_value, :float, :int, :int, Color.by_value], :void],
      [:DrawSphereWires, :DrawSphereWires, [Vector3.by_value, :float, :int, :int, Color.by_value], :void],
      [:DrawCylinder, :DrawCylinder, [Vector3.by_value, :float, :float, :float, :int, Color.by_value], :void],
      [:DrawCylinderEx, :DrawCylinderEx, [Vector3.by_value, Vector3.by_value, :float, :float, :int, Color.by_value], :void],
      [:DrawCylinderWires, :DrawCylinderWires, [Vector3.by_value, :float, :float, :float, :int, Color.by_value], :void],
      [:DrawCylinderWiresEx, :DrawCylinderWiresEx, [Vector3.by_value, Vector3.by_value, :float, :float, :int, Color.by_value], :void],
      [:DrawCapsule, :DrawCapsule, [Vector3.by_value, Vector3.by_value, :float, :int, :int, Color.by_value], :void],
      [:DrawCapsuleWires, :DrawCapsuleWires, [Vector3.by_value, Vector3.by_value, :float, :int, :int, Color.by_value], :void],
      [:DrawPlane, :DrawPlane, [Vector3.by_value, Vector2.by_value, Color.by_value], :void],
      [:DrawRay, :DrawRay, [Ray.by_value, Color.by_value], :void],
      [:DrawGrid, :DrawGrid, [:int, :float], :void],
      [:LoadModel, :LoadModel, [:pointer], Model.by_value],
      [:LoadModelFromMesh, :LoadModelFromMesh, [Mesh.by_value], Model.by_value],
      [:UnloadModel, :UnloadModel, [Model.by_value], :void],
      [:UnloadModelKeepMeshes, :UnloadModelKeepMeshes, [Model.by_value], :void],
      [:GetModelBoundingBox, :GetModelBoundingBox, [Model.by_value], BoundingBox.by_value],
      [:DrawModel, :DrawModel, [Model.by_value, Vector3.by_value, :float, Color.by_value], :void],
      [:rbDrawModelEx, :DrawModelEx, [Model.by_value, Vector3.by_value, Vector3.by_value, :float, Vector3.by_value, Color.by_value], :void],
      [:DrawModelWires, :DrawModelWires, [Model.by_value, Vector3.by_value, :float, Color.by_value], :void],
      [:DrawModelWiresEx, :DrawModelWiresEx, [Model.by_value, Vector3.by_value, Vector3.by_value, :float, Vector3.by_value, Color.by_value], :void],
      [:DrawBoundingBox, :DrawBoundingBox, [BoundingBox.by_value, Color.by_value], :void],
      [:DrawBillboard, :DrawBillboard, [Camera.by_value, Texture2D.by_value, Vector3.by_value, :float, Color.by_value], :void],
      [:DrawBillboardRec, :DrawBillboardRec, [Camera.by_value, Texture2D.by_value, Rectangle.by_value, Vector3.by_value, Vector2.by_value, Color.by_value], :void],
      [:DrawBillboardPro, :DrawBillboardPro, [Camera.by_value, Texture2D.by_value, Rectangle.by_value, Vector3.by_value, Vector3.by_value, Vector2.by_value, Vector2.by_value, :float, Color.by_value], :void],
      [:UploadMesh, :UploadMesh, [:pointer, :bool], :void],
      [:UpdateMeshBuffer, :UpdateMeshBuffer, [Mesh.by_value, :int, :pointer, :int, :int], :void],
      [:UnloadMesh, :UnloadMesh, [Mesh.by_value], :void],
      [:DrawMesh, :DrawMesh, [Mesh.by_value, Material.by_value, Matrix.by_value], :void],
      [:DrawMeshInstanced, :DrawMeshInstanced, [Mesh.by_value, Material.by_value, :pointer, :int], :void],
      [:ExportMesh, :ExportMesh, [Mesh.by_value, :pointer], :bool],
      [:GetMeshBoundingBox, :GetMeshBoundingBox, [Mesh.by_value], BoundingBox.by_value],
      [:GenMeshTangents, :GenMeshTangents, [:pointer], :void],
      [:GenMeshPoly, :GenMeshPoly, [:int, :float], Mesh.by_value],
      [:GenMeshPlane, :GenMeshPlane, [:float, :float, :int, :int], Mesh.by_value],
      [:GenMeshCube, :GenMeshCube, [:float, :float, :float], Mesh.by_value],
      [:GenMeshSphere, :GenMeshSphere, [:float, :int, :int], Mesh.by_value],
      [:GenMeshHemiSphere, :GenMeshHemiSphere, [:float, :int, :int], Mesh.by_value],
      [:GenMeshCylinder, :GenMeshCylinder, [:float, :float, :int], Mesh.by_value],
      [:GenMeshCone, :GenMeshCone, [:float, :float, :int], Mesh.by_value],
      [:GenMeshTorus, :GenMeshTorus, [:float, :float, :int, :int], Mesh.by_value],
      [:GenMeshKnot, :GenMeshKnot, [:float, :float, :int, :int], Mesh.by_value],
      [:GenMeshHeightmap, :GenMeshHeightmap, [Image.by_value, Vector3.by_value], Mesh.by_value],
      [:GenMeshCubicmap, :GenMeshCubicmap, [Image.by_value, Vector3.by_value], Mesh.by_value],
      [:LoadMaterials, :LoadMaterials, [:pointer, :pointer], :pointer],
      [:LoadMaterialDefault, :LoadMaterialDefault, [], Material.by_value],
      [:UnloadMaterial, :UnloadMaterial, [Material.by_value], :void],
      [:SetMaterialTexture, :SetMaterialTexture, [:pointer, :int, Texture2D.by_value], :void],
      [:SetModelMeshMaterial, :SetModelMeshMaterial, [:pointer, :int, :int], :void],
      [:LoadModelAnimations, :LoadModelAnimations, [:pointer, :pointer], :pointer],
      [:UpdateModelAnimation, :UpdateModelAnimation, [Model.by_value, ModelAnimation.by_value, :int], :void],
      [:UnloadModelAnimation, :UnloadModelAnimation, [ModelAnimation.by_value], :void],
      [:UnloadModelAnimations, :UnloadModelAnimations, [:pointer, :uint], :void],
      [:IsModelAnimationValid, :IsModelAnimationValid, [Model.by_value, ModelAnimation.by_value], :bool],
      [:CheckCollisionSpheres, :CheckCollisionSpheres, [Vector3.by_value, :float, Vector3.by_value, :float], :bool],
      [:CheckCollisionBoxes, :CheckCollisionBoxes, [BoundingBox.by_value, BoundingBox.by_value], :bool],
      [:CheckCollisionBoxSphere, :CheckCollisionBoxSphere, [BoundingBox.by_value, Vector3.by_value, :float], :bool],
      [:GetRayCollisionSphere, :GetRayCollisionSphere, [Ray.by_value, Vector3.by_value, :float], RayCollision.by_value],
      [:GetRayCollisionBox, :GetRayCollisionBox, [Ray.by_value, BoundingBox.by_value], RayCollision.by_value],
      [:GetRayCollisionMesh, :GetRayCollisionMesh, [Ray.by_value, Mesh.by_value, Matrix.by_value], RayCollision.by_value],
      [:GetRayCollisionTriangle, :GetRayCollisionTriangle, [Ray.by_value, Vector3.by_value, Vector3.by_value, Vector3.by_value], RayCollision.by_value],
      [:GetRayCollisionQuad, :GetRayCollisionQuad, [Ray.by_value, Vector3.by_value, Vector3.by_value, Vector3.by_value, Vector3.by_value], RayCollision.by_value],
      [:InitAudioDevice, :InitAudioDevice, [], :void],
      [:CloseAudioDevice, :CloseAudioDevice, [], :void],
      [:IsAudioDeviceReady, :IsAudioDeviceReady, [], :bool],
      [:SetMasterVolume, :SetMasterVolume, [:float], :void],
      [:LoadWave, :LoadWave, [:pointer], Wave.by_value],
      [:LoadWaveFromMemory, :LoadWaveFromMemory, [:pointer, :pointer, :int], Wave.by_value],
      [:LoadSound, :LoadSound, [:pointer], Sound.by_value],
      [:LoadSoundFromWave, :LoadSoundFromWave, [Wave.by_value], Sound.by_value],
      [:UpdateSound, :UpdateSound, [Sound.by_value, :pointer, :int], :void],
      [:UnloadWave, :UnloadWave, [Wave.by_value], :void],
      [:UnloadSound, :UnloadSound, [Sound.by_value], :void],
      [:ExportWave, :ExportWave, [Wave.by_value, :pointer], :bool],
      [:ExportWaveAsCode, :ExportWaveAsCode, [Wave.by_value, :pointer], :bool],
      [:PlaySound, :PlaySound, [Sound.by_value], :void],
      [:StopSound, :StopSound, [Sound.by_value], :void],
      [:PauseSound, :PauseSound, [Sound.by_value], :void],
      [:ResumeSound, :ResumeSound, [Sound.by_value], :void],
      [:PlaySoundMulti, :PlaySoundMulti, [Sound.by_value], :void],
      [:StopSoundMulti, :StopSoundMulti, [], :void],
      [:GetSoundsPlaying, :GetSoundsPlaying, [], :int],
      [:IsSoundPlaying, :IsSoundPlaying, [Sound.by_value], :bool],
      [:SetSoundVolume, :SetSoundVolume, [Sound.by_value, :float], :void],
      [:SetSoundPitch, :SetSoundPitch, [Sound.by_value, :float], :void],
      [:SetSoundPan, :SetSoundPan, [Sound.by_value, :float], :void],
      [:WaveCopy, :WaveCopy, [Wave.by_value], Wave.by_value],
      [:WaveCrop, :WaveCrop, [:pointer, :int, :int], :void],
      [:WaveFormat, :WaveFormat, [:pointer, :int, :int, :int], :void],
      [:LoadWaveSamples, :LoadWaveSamples, [Wave.by_value], :pointer],
      [:UnloadWaveSamples, :UnloadWaveSamples, [:pointer], :void],
      [:LoadMusicStream, :LoadMusicStream, [:pointer], Music.by_value],
      [:LoadMusicStreamFromMemory, :LoadMusicStreamFromMemory, [:pointer, :pointer, :int], Music.by_value],
      [:UnloadMusicStream, :UnloadMusicStream, [Music.by_value], :void],
      [:PlayMusicStream, :PlayMusicStream, [Music.by_value], :void],
      [:IsMusicStreamPlaying, :IsMusicStreamPlaying, [Music.by_value], :bool],
      [:UpdateMusicStream, :UpdateMusicStream, [Music.by_value], :void],
      [:StopMusicStream, :StopMusicStream, [Music.by_value], :void],
      [:PauseMusicStream, :PauseMusicStream, [Music.by_value], :void],
      [:ResumeMusicStream, :ResumeMusicStream, [Music.by_value], :void],
      [:SeekMusicStream, :SeekMusicStream, [Music.by_value, :float], :void],
      [:SetMusicVolume, :SetMusicVolume, [Music.by_value, :float], :void],
      [:SetMusicPitch, :SetMusicPitch, [Music.by_value, :float], :void],
      [:SetMusicPan, :SetMusicPan, [Music.by_value, :float], :void],
      [:GetMusicTimeLength, :GetMusicTimeLength, [Music.by_value], :float],
      [:GetMusicTimePlayed, :GetMusicTimePlayed, [Music.by_value], :float],
      [:LoadAudioStream, :LoadAudioStream, [:uint, :uint, :uint], AudioStream.by_value],
      [:UnloadAudioStream, :UnloadAudioStream, [AudioStream.by_value], :void],
      [:UpdateAudioStream, :UpdateAudioStream, [AudioStream.by_value, :pointer, :int], :void],
      [:IsAudioStreamProcessed, :IsAudioStreamProcessed, [AudioStream.by_value], :bool],
      [:PlayAudioStream, :PlayAudioStream, [AudioStream.by_value], :void],
      [:PauseAudioStream, :PauseAudioStream, [AudioStream.by_value], :void],
      [:ResumeAudioStream, :ResumeAudioStream, [AudioStream.by_value], :void],
      [:IsAudioStreamPlaying, :IsAudioStreamPlaying, [AudioStream.by_value], :bool],
      [:StopAudioStream, :StopAudioStream, [AudioStream.by_value], :void],
      [:SetAudioStreamVolume, :SetAudioStreamVolume, [AudioStream.by_value, :float], :void],
      [:SetAudioStreamPitch, :SetAudioStreamPitch, [AudioStream.by_value, :float], :void],
      [:SetAudioStreamPan, :SetAudioStreamPan, [AudioStream.by_value, :float], :void],
      [:SetAudioStreamBufferSizeDefault, :SetAudioStreamBufferSizeDefault, [:int], :void],
      [:SetAudioStreamCallback, :SetAudioStreamCallback, [AudioStream.by_value, :AudioCallback], :void],
      [:AttachAudioStreamProcessor, :AttachAudioStreamProcessor, [AudioStream.by_value, :AudioCallback], :void],
      [:DetachAudioStreamProcessor, :DetachAudioStreamProcessor, [AudioStream.by_value, :AudioCallback], :void],
    ]
    entries.each do |entry|
      begin
        attach_function entry[0], entry[1], entry[2], entry[3]
      rescue FFI::NotFoundError => error
        $stderr.puts("[Warning] Failed to import #{entry[0]} (#{error}).") if output_error
      end
    end
  end

end

