#
# For macOS + Xcode + CMake users.
#
mkdir -p build
cd build
export MACOSX_DEPLOYMENT_TARGET=14.0
cmake -D CMAKE_C_FLAGS="" -D CMAKE_BUILD_TYPE=Debug -D CMAKE_OSX_ARCHITECTURES="x86_64;arm64" -D BUILD_SHARED_LIBS=OFF -D BUILD_EXAMPLES=OFF -D CMAKE_C_COMPILER=clang ../raylib
# cmake -D CMAKE_C_FLAGS="" -D CMAKE_BUILD_TYPE=Release -D CMAKE_OSX_ARCHITECTURES="x86_64;arm64" -D BUILD_SHARED_LIBS=OFF -D BUILD_EXAMPLES=OFF -D CMAKE_C_COMPILER=clang ../raylib
make
